/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.proyect.view;

import ec.edu.espe.proyect.controller.SubjectController;
import javax.swing.JOptionPane;

/**
 *
 * @author Gabriela Sunta Future'sProgrammersTech ESPE- DCCO
 */
public class SubjectI extends javax.swing.JFrame {
    SubjectController subject = new SubjectController();

    /**
     * Creates new form Provider
     */
    public SubjectI() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNrc = new javax.swing.JTextField();
        txtNameSubject = new javax.swing.JTextField();
        txtTypeOfSchedule = new javax.swing.JTextField();
        txtDaysOfMatter = new javax.swing.JTextField();
        PnlButtomsProvider = new javax.swing.JPanel();
        BtmAdd = new javax.swing.JButton();
        BtmDelete = new javax.swing.JButton();
<<<<<<< HEAD:6.Code/ProyectStudentDataBase/src/ec/edu/espe/proyect/view/SubjectWindow.java
        BtmUpdate = new javax.swing.JButton();
        BtmDisplay = new javax.swing.JButton();
        btnBack1 = new javax.swing.JButton();
=======
>>>>>>> db3c26c6ca4e075707af352cd687ce3d08d5c378:6.Code/ProyectStudentDataBase/src/ec/edu/espe/proyect/view/SubjectI.java

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel1.setText("SUBJECT");

        jLabel2.setText("Nrc");

        jLabel3.setText("NameSuject");

        jLabel4.setText("Type Of Schedule");

        jLabel5.setText("Days Of Matter");

        txtNameSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameSubjectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(73, 73, 73)
                        .addComponent(txtNrc, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(txtDaysOfMatter, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNameSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTypeOfSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(105, 105, 105))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNrc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNameSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTypeOfSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtDaysOfMatter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        BtmAdd.setText("ADD");
        BtmAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtmAddActionPerformed(evt);
            }
        });

        BtmDelete.setText("DELETE");
        BtmDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtmDeleteActionPerformed(evt);
            }
        });

<<<<<<< HEAD:6.Code/ProyectStudentDataBase/src/ec/edu/espe/proyect/view/SubjectWindow.java
        BtmUpdate.setText("UPDATE");
        BtmUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtmUpdateActionPerformed(evt);
            }
        });

        BtmDisplay.setText("DISPLAY");
        BtmDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtmDisplayActionPerformed(evt);
            }
        });

        btnBack1.setText("BACK");
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });

=======
>>>>>>> db3c26c6ca4e075707af352cd687ce3d08d5c378:6.Code/ProyectStudentDataBase/src/ec/edu/espe/proyect/view/SubjectI.java
        javax.swing.GroupLayout PnlButtomsProviderLayout = new javax.swing.GroupLayout(PnlButtomsProvider);
        PnlButtomsProvider.setLayout(PnlButtomsProviderLayout);
        PnlButtomsProviderLayout.setHorizontalGroup(
            PnlButtomsProviderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlButtomsProviderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtmAdd)
                .addGap(109, 109, 109)
                .addComponent(BtmDelete)
<<<<<<< HEAD:6.Code/ProyectStudentDataBase/src/ec/edu/espe/proyect/view/SubjectWindow.java
                .addGap(68, 68, 68)
                .addComponent(BtmUpdate)
                .addGap(64, 64, 64)
                .addComponent(BtmDisplay)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBack1)
                .addGap(26, 26, 26))
=======
                .addGap(172, 172, 172))
>>>>>>> db3c26c6ca4e075707af352cd687ce3d08d5c378:6.Code/ProyectStudentDataBase/src/ec/edu/espe/proyect/view/SubjectI.java
        );
        PnlButtomsProviderLayout.setVerticalGroup(
            PnlButtomsProviderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlButtomsProviderLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(PnlButtomsProviderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtmDelete)
<<<<<<< HEAD:6.Code/ProyectStudentDataBase/src/ec/edu/espe/proyect/view/SubjectWindow.java
                    .addComponent(BtmUpdate)
                    .addComponent(BtmDisplay)
                    .addComponent(btnBack1))
                .addContainerGap(33, Short.MAX_VALUE))
=======
                    .addComponent(BtmAdd))
                .addContainerGap(41, Short.MAX_VALUE))
>>>>>>> db3c26c6ca4e075707af352cd687ce3d08d5c378:6.Code/ProyectStudentDataBase/src/ec/edu/espe/proyect/view/SubjectI.java
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlButtomsProvider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PnlButtomsProvider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameSubjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameSubjectActionPerformed

    private void BtmAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtmAddActionPerformed
        
        Integer nrc;
        String nameSubject, typeOfSchedule,daysOfMatter;
  
        if (txtNrc .getText().length() == 0 || txtNameSubject.getText().length() == 0 || 
                txtTypeOfSchedule.getText().length() == 0 || txtDaysOfMatter.getText().length() == 0){
           JOptionPane.showConfirmDialog(null, "Enter Information" , "OK", JOptionPane.DEFAULT_OPTION);
           BtmAdd.enable(false);
        } else{
            BtmAdd.enable(true);
            nrc = Integer.parseInt(this.txtNrc.getText());
            nameSubject = this.txtNameSubject.getText();
            typeOfSchedule = this.txtTypeOfSchedule.getText();
            daysOfMatter = this.txtDaysOfMatter.getText();
            
            subject.add(nrc, nameSubject, typeOfSchedule, daysOfMatter);
            
  }  
        txtNrc.setText("");
        txtNameSubject.setText("");
        txtDaysOfMatter.setText("");
        txtTypeOfSchedule.setText("");
        
                
                
                
    }//GEN-LAST:event_BtmAddActionPerformed

    private void BtmDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtmDeleteActionPerformed
        
         Integer nrcD = Integer.parseInt(JOptionPane.showInputDialog("Enter nrc to Delete"));
        subject.delete(nrcD); 
        
        
    }//GEN-LAST:event_BtmDeleteActionPerformed

<<<<<<< HEAD:6.Code/ProyectStudentDataBase/src/ec/edu/espe/proyect/view/SubjectWindow.java
    private void BtmUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtmUpdateActionPerformed
        
        
         Integer nrcU = Integer.parseInt(JOptionPane.showInputDialog("Enter nrc  to update"));
        String nameSubjectU = JOptionPane.showInputDialog("Enter nameSubject of product to update");
       subject.update(nrcU, nameSubjectU);
        
    }//GEN-LAST:event_BtmUpdateActionPerformed

    private void BtmDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtmDisplayActionPerformed
       subject.display(txtAreaProvider);
    }//GEN-LAST:event_BtmDisplayActionPerformed

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        StudenySystem studenySystem = new StudenySystem();
        studenySystem.setVisible(true);
    }//GEN-LAST:event_btnBack1ActionPerformed

=======
>>>>>>> db3c26c6ca4e075707af352cd687ce3d08d5c378:6.Code/ProyectStudentDataBase/src/ec/edu/espe/proyect/view/SubjectI.java
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SubjectI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SubjectI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SubjectI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SubjectI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SubjectI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtmAdd;
    private javax.swing.JButton BtmDelete;
    private javax.swing.JPanel PnlButtomsProvider;
    private javax.swing.JButton btnBack1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtDaysOfMatter;
    private javax.swing.JTextField txtNameSubject;
    private javax.swing.JTextField txtNrc;
    private javax.swing.JTextField txtTypeOfSchedule;
    // End of variables declaration//GEN-END:variables
}

